import { useState } from "react";
import DiceButton from "./DiceButton";
import ResultDisplay from "./ResultDisplay";
import "./DiceDashboard.css";

const DiceDashboard = () => {
  const [currentResult, setCurrentResult] = useState(null);
  const [rollHistory, setRollHistory] = useState([]);

  // Tablas d100 para Aventura de Superhéroes en el Espacio
  const diceData = [
    {
      id: "scifi_nouns",
      name: "Sustantivos Sci-Fi",
      icon: "🌌",
      items: [
        "Nebulosa",
        "Asteroide",
        "Cometa",
        "Exoplaneta",
        "Galaxia",
        "Cuásar",
        "Púlsar",
        "Agujero",
        "Singularidad",
        "Estación",
        "Orbital",
        "Colonia",
        "Hábitat",
        "Sector",
        "Bifurcación",
        "Anomalía",
        "Portal",
        "Hipereje",
        "Salto",
        "Túnel",
        "Ruta",
        "Senda",
        "Vía",
        "Convergencia",
        "Divergencia",
        "Falla",
        "Cámara",
        "Nave",
        "Módulo",
        "Cápsula",
        "Motor",
        "Reactor",
        "Propulsor",
        "Escudo",
        "Arma",
        "Sensor",
        "Consola",
        "Terminal",
        "Interfaz",
        "Dron",
        "Robot",
        "IA",
        "Ciborg",
        "Droide",
        "Unidad",
        "Muestra",
        "Cristal",
        "Mineral",
        "Aleación",
        "Reliquia",
        "Artefacto",
        "Ruina",
        "Templo",
        "Glifo",
        "Símbolo",
        "Código",
        "Datos",
        "Registro",
        "Bitácora",
        "Archivo",
        "Espectro",
        "Campo",
        "Onda",
        "Energía",
        "Radiación",
        "Partícula",
        "Materia",
        "Antimateria",
        "Vórtice",
        "Grieta",
        "Erupción",
        "Pulso",
        "Resonancia",
        "Eco",
        "Señal",
        "Mensaje",
        "Advertencia",
        "Amenaza",
        "Criatura",
        "Especie",
        "Forma",
        "Entidad",
        "Civilización",
        "Imperio",
        "Federación",
        "Alianza",
        "Conflicto",
        "Guerra",
        "Paz",
        "Tratado",
        "Acuerdo",
        "Misión",
        "Objetivo",
        "Descubrimiento",
        "Hallazgo",
        "Recompensa",
        "Peligro",
        "Desafío",
        "Solución",
        "Elemento"
      ]
    },
    {
      id: "ship_events",
      name: "Eventos en la Nave",
      icon: "�",
      items: [
        "Fallo en el motor principal",
        "Despresurización de un compartimento",
        "Tormenta de radiación solar",
        "Ataque de piratas espaciales",
        "Impacto de micrometeorito",
        "Fallo en el soporte vital",
        "Intruso a bordo",
        "Mal funcionamiento del sistema de navegación",
        "Cortocircuito generalizado",
        "Explosión en la sala de máquinas",
        "Comunicación interrumpida",
        "Error en el replicador de alimentos",
        "Enjambre de insectos cósmicos",
        "IA de la nave se vuelve errática",
        "Señal de socorro falsa",
        "Despertar de un pasajero en estasis",
        "Virus informático alienígena",
        "El supercombustible reacciona",
        "Gravedad fluctuante",
        "Fallo en los escudos defensores",
        "Aparición de un fantasma espacial",
        "Compuerta de carga se abre accidentalmente",
        "Sistema de contención falla",
        "Robot de servicio se rebela",
        "Filtración de agua reciclada",
        "Las luces parpadean incesantemente",
        "Ruido misterioso en el casco",
        "Piloto automático se desconecta",
        "Fallo en la climatización",
        "Consumo excesivo de energía",
        "Nave entra en un campo de escombros",
        "Un miembro sufre una pesadilla lúcida",
        "Sistemas de seguridad se bloquean",
        "Detección de una nave oculta cercana",
        "Un objeto personal se pierde",
        "Las cámaras de vigilancia se oscurecen",
        "Una planta muta a bordo",
        "Un portal dimensional se abre brevemente",
        "Aparición de un temporal espacial",
        "Bomba de tiempo oculta",
        "La nave es remolcada",
        "Fallo en los inyectores de plasma",
        "Residuos tóxicos se liberan",
        "Una ilusión óptica afecta a la tripulación",
        "Sistemas de teletransporte se activan solos",
        "Mascota de la nave se vuelve salvaje",
        "Fallo en los propulsores de maniobra",
        "Una sustancia pegajosa cubre un área",
        "Un holograma errante aparece",
        "Los sistemas de defensa apuntan a la propia nave",
        "Fallo en el reciclador de aire",
        "Sensores detectan vida a bordo",
        "La nave se congela gradualmente",
        "Sistemas de comunicación reciben una canción extraña",
        "Se rompe una tubería principal",
        "La computadora de la nave pide ayuda",
        "Un módulo se desprende parcialmente",
        "Cristales extraños crecen en el casco",
        "Una criatura espacial se adhiere a la nave",
        "Los controles de la nave se invierten",
        "El campo de fuerza de la bodega falla",
        "Luces estroboscópicas incontrolables",
        "Sistemas de armas se activan por sí solos",
        "Un miembro del equipo enferma de repente",
        "La nave entra en un campo de partículas desconocidas",
        "La presión arterial de la tripulación sube",
        "Se escuchan susurros en los conductos",
        "Un experimento científico a bordo sale mal",
        "La nave es arrastrada por una corriente cósmica",
        "Fallo en los propulsores de atraque",
        "Un objeto levita dentro de la nave",
        "Los escáneres detectan un ser dentro de un muro",
        "El generador de gravedad falla en una sección",
        "Una luz brillante inunda la nave",
        "Fuga de un gas adormecedor",
        "Se activa un sistema de defensa antiguo",
        "Una visión apocalíptica se proyecta",
        "Los nanobots de mantenimiento se vuelven locos",
        "Se detecta una nave idéntica",
        "La nave empieza a emitir un campo estático",
        "Alguien deja una nota de advertencia críptica",
        "Fallo en los inhibidores de poder",
        "Un dispositivo de camuflaje se activa aleatoriamente",
        "Una grieta temporal se abre",
        "Se pierde el control de los drones",
        "La nave se convierte en un imán",
        "Una anomalía energética hace que los sueños se hagan realidad",
        "Los sistemas de compresión de basura se desbordan",
        "Un replicador de objetos crea duplicados imperfectos",
        "La IA de la nave pide un favor inusual",
        "Un haz de energía desconocido golpea la nave",
        "Se activa un sistema de clonación experimental",
        "El suministro de agua se contamina",
        "Se activa un campo de distorsión del sonido",
        "La nave queda atrapada en una red de energía alienígena",
        "Un cargamento de armas exóticas se activa",
        "La nave empieza a cantar",
        "Un artefacto a bordo se activa solo",
        "Las luces de la nave cambian de color",
        "La nave se desvía a una dimensión espejo"
      ]
    },
    {
      id: "discoveries",
      name: "Descubrimientos",
      icon: "🔍",
      items: [
        "Restos de una megaciudad alienígena",
        "Una biosfera artificial gigante",
        "Un cementerio de naves espaciales",
        "Una estación de investigación científica oculta",
        "Un planeta cubierto de hielo",
        "Un asteroide hueco",
        "Una nebulosa de colores vibrantes",
        "Un puesto de avanzada de la Tierra olvidado",
        "Un planeta con una atmósfera de gas tóxico",
        "La fuente del supercombustible",
        "Un agujero de gusano inestable",
        "Una biblioteca galáctica antigua",
        "Un planeta volcánico",
        "Una prisión de máxima seguridad alienígena",
        "Un satélite artificial que emite música",
        "Los restos de una batalla estelar masiva",
        "Un planeta con una civilización primitiva",
        "Una zona del espacio donde el tiempo se ralentiza",
        "Una nave espacial de exploración estrellada",
        "Un planeta desierto",
        "Un vivero espacial gigante",
        "Una anomalía espacial que duplica objetos",
        "Un planeta oceánico",
        "Un puesto de observación secreto",
        "Un sistema estelar binario",
        "Una esfera Dyson incompleta",
        "Un campo de escombros de una estación espacial",
        "Un planeta con tecnología que interactúa con las mentes",
        "Una zona de silencio espacial",
        "La fuente del supercombustible en un nido",
        "Una colonia humana renegada",
        "Un planeta con una atmósfera que modifica los poderes",
        "Un cinturón de asteroides con una densidad de vida increíble",
        "Un sistema planetario con planetas gigantes gaseosos",
        "Un planeta con una única especie dominante",
        "Una nave de investigación abandonada",
        "Un agujero negro errante",
        "Un planeta que es una única y gigantesca forma de vida",
        "Una fábrica automatizada alienígena",
        "La fuente del supercombustible en una anomalía temporal",
        "Un santuario de una religión alienígena",
        "Un planeta con clima impredecible",
        "Una base de contrabando intergaláctico",
        "Un planetoide que es en realidad un huevo gigante",
        "Un campo de fuerza invisible",
        "Una zona del espacio llena de ilusiones",
        "Un planeta con una red subterránea de túneles",
        "Los restos de un coloso espacial",
        "Un planeta que emite una frecuencia extraña",
        "La fuente del supercombustible dentro de una criatura espacial",
        "Una colonia minera enloquecida",
        "Un campo de asteroides con trampas",
        "Un planeta con ciudades flotantes",
        "Una nave prisión a la deriva",
        "Un sistema solar con solo un planeta",
        "Un nido de naves alienígenas dormidas",
        "Un planeta con una anomalía gravitacional",
        "Una señal de radio antigua",
        "Un templo alienígena sumergido",
        "La fuente del supercombustible en un volcán activo",
        "Un campo de energía que desactiva la tecnología",
        "Un planeta con una especie que absorbe energía",
        "Un área del espacio con fragmentos de planetas",
        "Una estación de servicio de naves",
        "Un planeta con una flora que emite gases alucinógenos",
        "Un mercado negro espacial flotante",
        "Un planeta que es un gigantesco cerebro",
        "Una burbuja de realidad alternativa",
        "Una civilización alienígena en guerra civil",
        "La fuente del supercombustible en un sol moribundo",
        "Un planeta con un guardián robótico",
        "Un oasis espacial",
        "Un planeta que cambia de forma",
        "Una nave arca que transporta especies extintas",
        "Un área del espacio donde los colores se distorsionan",
        "Un planeta donde la tecnología no funciona",
        "Una fábrica de drones descontrolada",
        "Un planeta habitado por sombras",
        "Un sistema de agujeros negros interconectados",
        "La fuente del supercombustible en un plano etéreo",
        "Un laboratorio de experimentación genética",
        "Un planeta que es una trampa de un depredador gigante",
        "Un portal antiguo que lleva a una galaxia lejana",
        "Una estación de retransmisión de emergencia",
        "Un campo de minas espaciales activas",
        "Un planeta con estructuras cristalinas gigantes",
        "Una nave espacial legendaria o mítica",
        "Un planeta con una flora que se alimenta de metales",
        "Un campo de energía que causa amnesia",
        "La fuente del supercombustible es un ser vivo",
        "Una ciudad bajo la superficie de un planeta",
        "Un planeta que es una simulación perfecta",
        "Una zona del espacio donde los poderes no funcionan",
        "Un monumento flotante a una civilización perdida",
        "Un planeta con una inteligencia colectiva",
        "Una baliza de emergencia antigua",
        "Un planeta con una atmósfera que amplifica el sonido",
        "Una anomalía que fusiona dos realidades",
        "Un campo de entrenamiento de superhéroes encubierto",
        "La fuente del supercombustible es una parte del universo"
      ]
    },
    {
      id: "obstacles",
      name: "Obstáculos",
      icon: "⚠️",
      items: [
        "Bloqueo militar",
        "Trampa mortal",
        "Falla del equipo crucial",
        "Enigma ancestral",
        "Criatura guardian",
        "Entorno hostil",
        "Falta de recursos",
        "Rivalidad de facciones",
        "Tiempo limitado",
        "Dilema moral",
        "Virus informático",
        "Desactivar un sistema de seguridad",
        "Negociación difícil",
        "Persecución incesante",
        "Campo de fuerza impenetrable",
        "Un aliado se convierte en enemigo",
        "Un experimento científico descontrolado",
        "El elemento es inestable",
        "Rescate de rehenes",
        "Desactivar una bomba",
        "Prueba de fe o valor",
        "Interferencia de poderes",
        "Zona de silencio tecnológico",
        "Engaño o ilusión",
        "Caza de reliquias",
        "Sabotaje interno",
        "Meteoros en trayectoria de colisión",
        "Un laberinto espacial",
        "Necesidad de un sacrificio",
        "El elemento es consciente",
        "Control mental",
        "Un evento gravitacional anómalo",
        "Desactivar un campo de camuflaje",
        "Prueba de habilidad",
        "El objetivo está en un lugar inaccesible",
        "Pistas crípticas",
        "Una enfermedad o plaga alienígena",
        "Un guardián invulnerable",
        "El elemento es un ser vivo",
        "Traición de un aliado",
        "Un campo de energía que invierte los poderes",
        "La nave es arrastrada por un rayo tractor",
        "Un código genético necesario",
        "El entorno cambia constantemente",
        "Un sistema de drones defensivos",
        "Una tormenta electromagnética",
        "La criatura que buscáis es invisible",
        "Una zona de gravedad cero controlada",
        "El elemento es una trampa",
        "Una profecía oscura",
        "Resistencia de la población local",
        "Un temporal de arena cósmica",
        "Falla en el sistema de camuflaje de la nave",
        "Un sistema de trampas de sonido",
        "El elemento es un duplicado",
        "Un campo de mutación espontánea",
        "Necesidad de un ritual o ceremonia",
        "Una civilización que vive en el vacío",
        "El elemento es un parásito",
        "Un laberinto de espejos distorsionadores",
        "Un volcán espacial entra en erupción",
        "Los sistemas de soporte vital fallan",
        "Un campo de estática psíquica",
        "La nave está siendo drenada de energía",
        "Un portal se abre y libera criaturas",
        "El objetivo requiere una fuerza específica",
        "Una cadena montañosa de cristal",
        "La gravedad del planeta es extrema",
        "Una criatura gigante os persigue",
        "El elemento está protegido por un sistema ancestral",
        "Una nube de nanobots hostiles",
        "Un dilema ético con androides",
        "El objetivo está en el centro de un nido de asteroides",
        "Necesidad de viajar en el tiempo",
        "Un ser cósmico os pone a prueba",
        "El elemento requiere una resonancia específica",
        "Una enfermedad que afecta a la percepción",
        "Un campo de distorsión espacial",
        "Los escáneres están enloquecidos",
        "El elemento está fusionado con un ser vivo",
        "Una red de cables de energía mortales",
        "El planeta se desestabiliza",
        "Un culto alienígena adora el elemento",
        "Una zona con radiación que anula los poderes",
        "Se activa un sistema de teletransporte fallido",
        "El objetivo está sumergido en un océano cáustico",
        "Una barrera de tiempo",
        "Los robots de mantenimiento se vuelven hostiles",
        "El elemento atrae a una criatura gigante",
        "Necesidad de un sacrificio heroico",
        "Un campo de asteroides con vida propia",
        "El elemento se ha integrado en un ecosistema",
        "Una máquina de guerra antigua se activa",
        "Un campo de sonido que paraliza",
        "La memoria de un miembro se borra",
        "El elemento está en un universo de bolsillo",
        "Una entidad cósmica os observa",
        "Un engaño complejo",
        "Los poderes de los héroes son drenados",
        "El elemento es el propio destino"
      ]
    },
    {
      id: "plot_twists",
      name: "Giros de Trama",
      icon: "🎭",
      items: [
        "El supercombustible es un ser vivo y consciente",
        "Uno de los héroes es un impostor o un agente doble",
        "La Tierra ya no existe o ha sido destruida mientras estabais fuera",
        "El Elemento es en realidad un arma de destrucción masiva",
        "La misión no es de exploración, sino de colonización forzada",
        "La nave está siendo controlada por una IA renegada a bordo",
        "El objetivo de la misión es una trampa de una civilización enemiga",
        "Un miembro del equipo ha mutado por el espacio o el Elemento",
        "La Tierra os miente sobre la verdadera naturaleza del Elemento",
        "El Elemento es el huevo o crisálida de una criatura gigante",
        "Descubrís que sois clones o productos de un experimento",
        "El enemigo principal es, en realidad, un héroe caído de la Tierra",
        "El Elemento tiene un efecto secundario devastador en los héroes",
        "La realidad es una simulación creada por una entidad superior",
        "La nave está viajando en el tiempo sin que lo sepáis",
        "El Elemento no es un combustible, sino un catalizador para una invasión",
        "Uno de vuestros aliados alienígenas os traiciona",
        "El Elemento necesita ser destruido, no recuperado",
        "La misión ya fue completada en el pasado por otro equipo",
        "El Elemento es una cura para una plaga desconocida",
        "El enemigo os estaba protegiendo del Elemento",
        "Los héroes tienen un recuerdo falso implantado",
        "La nave es un experimento viviente y está evolucionando",
        "El Elemento es un portal a otra dimensión",
        "La Tierra busca vengarse de una antigua afrenta alienígena",
        "La nave contiene un ser antiguo en estasis",
        "El Elemento absorbe poderes de los superhéroes cercanos",
        "El capitán es un impostor o está comprometido",
        "Descubrís que vuestra presencia crea paradojas temporales",
        "El Elemento es parte de un organismo galáctico gigante",
        "Hay una facción secreta a bordo trabajando en contra",
        "Los villanos os están ayudando sin que lo sepáis",
        "El Elemento no es escaso, sino común, y la Tierra miente",
        "La nave es un señuelo para desviar la atención de algo más",
        "Uno de los héroes es el verdadero villano encubierto",
        "El Elemento transforma la materia a su alrededor",
        "El Elemento es la clave para despertar a una fuerza dormida",
        "Vuestro pasado heroico es una farsa montada",
        "El Elemento es un dispositivo de comunicación alienígena",
        "La Tierra os envió a un suicidio programado",
        "El Elemento se adhiere a un héroe y lo convierte en su huésped",
        "El viaje no es espacial, sino submarino o subterráneo",
        "Los poderes de los héroes provienen del Elemento",
        "Hay otro equipo de superhéroes de la Tierra que os persigue",
        "El Elemento es el núcleo de un planeta vivo",
        "La misión es una prueba moral impuesta por una entidad",
        "La nave tiene clones ocultos de la tripulación",
        "El Elemento crea ilusiones o realidades alternativas",
        "El supercombustible es una plaga que se extiende",
        "El Elemento es un registro de una civilización antigua",
        "Un cadáver reanimado de un miembro de la tripulación",
        "El Elemento es un espejo de los miedos de los héroes",
        "La misión es una distracción para una invasión mayor",
        "El Elemento es un arma biológica fallida",
        "Hay una sociedad secreta dentro de la tripulación",
        "El Elemento es la mente colmena de una especie hostil",
        "La nave se convierte en un ser consciente",
        "El Elemento cambia de forma o propiedades constantemente",
        "La Tierra es controlada por una entidad alienígena",
        "El Elemento es un portal bidireccional",
        "Un antiguo enemigo de la Tierra reaparece inesperadamente",
        "El Elemento es un medio de transporte para algo peligroso",
        "Los registros de la misión son falsos",
        "El Elemento otorga poderes incontrolables a quien lo toca",
        "La misión es una búsqueda personal de alguien importante",
        "El Elemento es la fuente de un mito galáctico",
        "La nave tiene un compartimento secreto con un fin oscuro",
        "El Elemento requiere un sacrificio para ser obtenido",
        "Los alienígenas que lo protegen son refugiados",
        "El Elemento es la llave para desatar un cataclismo",
        "Descubrís que no podéis volver a la Tierra",
        "El Elemento es una planta o flora sensible",
        "Los poderes de los héroes se anulan cerca del Elemento",
        "La nave es un museo de la historia galáctica",
        "El Elemento es una trampa de los propios creadores",
        "Un mensaje del futuro se recibe a través del Elemento",
        "El Elemento tiene un gemelo maligno",
        "La nave es una prisión flotante para el Elemento",
        "El Elemento tiene la capacidad de manipular la realidad",
        "Los superhéroes fueron creados para esta misión",
        "El Elemento es el corazón de un universo en miniatura",
        "Un miembro de la tripulación tiene una agenda oculta",
        "La Tierra fue atacada por lo que estáis buscando",
        "El Elemento es un artefacto que reescribe la historia",
        "La nave está habitada por seres interdimensionales",
        "El Elemento es la causa de una antigua guerra galáctica",
        "Uno de los personajes tiene una conexión psíquica con el Elemento",
        "La misión es una farsa para ocultar otra operación",
        "El Elemento es un recuerdo colectivo de una civilización",
        "La nave es un refugio para una especie en extinción",
        "El Elemento absorbe la fuerza vital de los seres cercanos",
        "La Tierra os envió a traicionar a una raza alienígena",
        "El Elemento es una semilla que creará un nuevo universo",
        "Un error en el cronómetro significa que el tiempo es diferente",
        "El Elemento es el núcleo de un falso dios",
        "Los héroes son parte de un plan que va más allá de la misión",
        "El Elemento es un registro de la extinción de una especie",
        "La nave es una cápsula del tiempo de una civilización",
        "El Elemento es el catalizador de una nueva evolución",
        "El Elemento es vuestro reflejo distorsionado o mejorado"
      ]
    },
    {
      id: "spaceship_forms",
      name: "Formas de Naves",
      icon: "🛸",
      items: [
        "Esfera perfecta",
        "Cigarro/Cilindro alargado",
        "Ala voladora gigante",
        "Pirámide flotante",
        "Anillo orbital",
        "Calavera orgánica",
        "Cristal gigante",
        "Araña mecánica",
        "Ciudad flotante",
        "Flor metálica",
        "Platillo volante",
        "Hueso de pez gigante",
        "Serpiente espacial",
        "Constelación de módulos",
        "Libélula",
        "Nube de escombros controlada",
        "Dodecaedro perfecto",
        "Roca espacial modificada",
        "Aguja flotante",
        "Mano abierta",
        "Rueda gigante",
        "Medusa espacial",
        "Enjambre de drones",
        "Martillo de guerra",
        "Escudo volador",
        "Templo flotante",
        "Mariposa",
        "Jaula de energía",
        "Copo de nieve simétrico",
        "Huevo resplandeciente",
        "Taladro gigante",
        "Arco tensado",
        "Corazón pulsante",
        "Gota de mercurio",
        "Colmena flotante",
        "Pez volador",
        "Tejido interdimensional",
        "Cubo distorsionado",
        "Jarra con asa",
        "Burbuja iridiscente",
        "Flor de loto abierta",
        "Masa amorfa",
        "Ancla gigante",
        "Escorpión",
        "Gema tallada",
        "Ojo flotante",
        "Reloj de arena",
        "Hoja de árbol",
        "Copo de nieve asimétrico",
        "Cápsula de semilla",
        "Tren espacial",
        "Barco velero",
        "Pluma gigante",
        "Caracola espiral",
        "Gárgola metálica",
        "Nido de aves",
        "Araña de cristal",
        "Libro abierto",
        "Cáliz o copa",
        "Daga o espada",
        "Lámpara de araña",
        "Colmena tubular",
        "Rata espacial",
        "Vaso de precipitados",
        "Corona o tiara",
        "Paraguas gigante",
        "Carroza antigua",
        "Búho mecánico",
        "Barco de pesca",
        "Molino de viento",
        "Pájaro prehistórico",
        "Estrella de mar",
        "Armadura de caballero",
        "Faro cósmico",
        "Cueva voladora",
        "Esqueleto de animal gigante",
        "Guantelete cerrado",
        "Nave con tentáculos",
        "Árbol flotante",
        "Cometa artificial",
        "Báculo mágico",
        "Aro rodante",
        "Escama de dragón",
        "Fortaleza volante",
        "Esfera rota",
        "Joya tallada",
        "Tubería gigante",
        "Estetoscopio",
        "Gota de sangre",
        "Engranaje giratorio",
        "Caracola de mar",
        "Catedral gótica",
        "Ojo de cerradura",
        "Tótem antiguo",
        "Cisne espacial",
        "Máscara ceremonial",
        "Reloj de sol",
        "Red gigante",
        "Escultura abstracta",
        "La propia constelación de estrellas"
      ]
    },
    {
      id: "alien_life",
      name: "Vida Extraterrestre",
      icon: "👽",
      items: [
        "Humanos con piel azul/verde",
        "Elfos espaciales",
        "Enanos cósmicos",
        "Reptilianos",
        "Insectoides bípedos",
        "Felinos humanoides",
        "Avianos humanoides",
        "Anfibios humanoides",
        "Vegetales andantes",
        "Seres de energía pura",
        "Ciborgs nativos",
        "Gigantes de roca",
        "Sombras cambiantes",
        "Seres de luz estelar",
        "Humanoides de cristal",
        "Psíquicos etéreos",
        "Seres arbóreos",
        "Vampiros cósmicos",
        "Ingenieros genéticos",
        "Viajeros temporales",
        "Seres de gas condensado",
        "Tecno-orgánicos",
        "Alquimistas dimensionales",
        "Piratas galácticos",
        "Cazadores furtivos",
        "Comerciantes de información",
        "Guardianes ancestrales",
        "Exiliados de una civilización avanzada",
        "Seres de memoria colectiva",
        "Exploradores intrépidos",
        "Artistas de la realidad",
        "Constructores de mundos",
        "Pacifistas tecnológicos",
        "Guerreros de honor",
        "Nómadas espaciales",
        "Curanderos empáticos",
        "Manipuladores de sombras",
        "Cultivadores de cristales",
        "Criadores de bestias",
        "Mensajeros cósmicos",
        "Bibliotecarios vivientes",
        "Sonámbulos estelares",
        "Tejedores de redes de energía",
        "Forjadores de estrellas",
        "Seres de vacío",
        "Cuentacuentos astrales",
        "Cantantes resonantes",
        "Guardianes de portales",
        "Escultores de la luz",
        "Los propios humanos del futuro",
        "Criatura ameboide gigante",
        "Serpiente espacial de metal",
        "Enjambre de insectos voladores",
        "Medusa espacial",
        "Gusano de arena cósmico",
        "Flor carnívora gigante",
        "Araña de cristal",
        "Bestia de cuatro brazos",
        "Molusco inteligente",
        "Esfera con tentáculos oculares",
        "Roca que cobra vida",
        "Seres de energía pura",
        "Nube de esporas inteligentes",
        "Criatura simbiótica",
        "Golem mecánico viviente",
        "Parásito mental",
        "Planta sensible y móvil",
        "Depredador camuflador",
        "Microorganismos conscientes",
        "Bestia con múltiples bocas/ojos",
        "Ser de sombra",
        "Árboles andantes",
        "Gusanos de luz",
        "Colmena inteligente",
        "Criatura magnética",
        "Esqueleto viviente",
        "Ser de cristal resonante",
        "Bestia de plasma",
        "Criatura que cambia de fase",
        "Cangrejo gigante",
        "Babuino espacial",
        "Pez volador",
        "Seres de humo o niebla",
        "Depredador que imita voces",
        "Esponja cósmica",
        "Criatura biomecánica",
        "Seres que viven en el vacío",
        "Planta con conciencia",
        "Gusanos segmentados gigantes",
        "Organismo que manipula la gravedad",
        "Seres de arcilla o lodo",
        "Criatura que se alimenta de recuerdos",
        "Aves gigantes con garras de energía",
        "Insectos que construyen naves",
        "Seres de sonido",
        "Criaturas invisibles hasta que se alimentan",
        "Seres que viven en el tiempo",
        "Plantas carnívoras con inteligencia",
        "Organismo que forma planetas",
        "El Elemento en sí es una forma de vida extraterrestre"
      ]
    }
  ];

  const handleDiceRoll = (diceName, result, sides) => {
    const newResult = {
      diceName,
      result,
      sides,
      timestamp: new Date().toLocaleTimeString()
    };

    setCurrentResult(newResult);
    setRollHistory((prev) => [newResult, ...prev.slice(0, 4)]); // Mantener solo los últimos 5 resultados
  };

  return (
    <div className="dice-dashboard">
      <ResultDisplay currentResult={currentResult} />

      <div className="dice-grid">
        {diceData.map((dice) => (
          <DiceButton
            key={dice.id}
            name={dice.name}
            icon={dice.icon}
            items={dice.items}
            onRoll={handleDiceRoll}
          />
        ))}
      </div>

      {rollHistory.length > 0 && (
        <div className="roll-history">
          <h3>Últimos resultados</h3>
          <div className="history-list">
            {rollHistory.map((roll, index) => (
              <div key={index} className="history-item">
                <span className="history-dice">{roll.diceName}</span>
                <span className="history-result">{roll.result}</span>
                <span className="history-time">{roll.timestamp}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default DiceDashboard;
